// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdPgRLLQXD40LBtWSndCMlfq0OfprXkkc',
    appId: '1:927992387719:web:8fb51790529f355f620022',
    messagingSenderId: '927992387719',
    projectId: 'menu-master-9c309',
    authDomain: 'menu-master-9c309.firebaseapp.com',
    storageBucket: 'menu-master-9c309.appspot.com',
    measurementId: 'G-ERR6SXSHHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPYC8gHOXCqk2fEhvy2i36JuIkQHEvsA',
    appId: '1:927992387719:android:2c425786685a4a02620022',
    messagingSenderId: '927992387719',
    projectId: 'menu-master-9c309',
    storageBucket: 'menu-master-9c309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA04OZ1Oev03gMJQj-EEiZDbyrjIzDLY4s',
    appId: '1:927992387719:ios:2ff88f0baebb6b79620022',
    messagingSenderId: '927992387719',
    projectId: 'menu-master-9c309',
    storageBucket: 'menu-master-9c309.appspot.com',
    androidClientId: '927992387719-dmfqbek07kct46vnvcqnuc87h943udb1.apps.googleusercontent.com',
    iosClientId: '927992387719-2b4i6alo0d3r00rlu313g0tk6qegat48.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA04OZ1Oev03gMJQj-EEiZDbyrjIzDLY4s',
    appId: '1:927992387719:ios:2ff88f0baebb6b79620022',
    messagingSenderId: '927992387719',
    projectId: 'menu-master-9c309',
    storageBucket: 'menu-master-9c309.appspot.com',
    androidClientId: '927992387719-dmfqbek07kct46vnvcqnuc87h943udb1.apps.googleusercontent.com',
    iosClientId: '927992387719-2b4i6alo0d3r00rlu313g0tk6qegat48.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuMaster',
  );
}
